include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    # always_put_required_named_parameters_first: false
    constant_identifier_names: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Setting this to true will require your variable types explicitly
    # always_specify_types: false

    # Back to the 80s
    lines_longer_than_80_chars: false

    empty_statements: true

    non_constant_identifier_names: true

    null_closures: true

    unnecessary_new: true

    unnecessary_overrides: true

    avoid_empty_else: true

    # Opt for DebugPrint instead
    avoid_print: true

    # Close all open streams as it ends up emitting data that no one observes and leaks memory
    close_sinks: true
