name: ojembaa_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter_riverpod: ^2.4.2
  flutter_svg: ^2.0.7
  http: ^1.1.0
  http_parser: ^4.0.2
  intl: ^0.18.1
  image_picker: ^1.0.4
  path: ^1.8.3
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter 
  riverpod_lint: ^2.3.3
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

 
  fonts:
    - family: QanelasSoft
      fonts:
        - asset: assets/fonts/QanelasSoft-Thin.otf
          weight: 100
        - asset: assets/fonts/QanelasSoft-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/QanelasSoft-Light.otf
          weight: 300
        - asset: assets/fonts/QanelasSoft-Regular.otf
          weight: 400
        - asset: assets/fonts/QanelasSoft-Medium.otf
          weight: 500
        - asset: assets/fonts/QanelasSoft-SemiBold.otf
          weight: 600
        - asset: assets/fonts/QanelasSoft-Bold.otf
          weight: 700
        - asset: assets/fonts/QanelasSoft-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/QanelasSoft-Black.otf
          weight: 900
 